#!/bin/sh

SCRIPTPATH="$(readlink -f 2>/dev/null "$0" || perl -MCwd -e 'print Cwd::abs_path shift' "$0")"
SCRIPTDIR="$(dirname "${SCRIPTPATH}")"

GITHUB_USER="$1"
PREFIX="$2"
EXCLUDE_REPOS="$3"
if test "x${GITHUB_USER}" = "x"
then
	echo "Usage: $0 GITHUB_USER LOCAL_PATH_PREFIX [EXCLUDE_REPOS]"
	exit 2
fi

GITHUB_URL="https://github.com/"

REPOS="$(curl -s -f "https://api.github.com/users/${GITHUB_USER}/repos" | jq -r '.[].full_name')"

for r in $REPOS
do
	ignore=0
	if test "x${EXCLUDE_REPOS}" != "x"; then
		echo "${r}" | grep -E "${EXCLUDE_REPOS}" >/dev/null
		if test "x$?" = "x0"; then
			echo "# ignore repo: ${r}"
			ignore=1
		fi
	fi

	if test "x${ignore}" != "x1"; then
		"${SCRIPTDIR}/backup-git-repo" "${GITHUB_URL}${r}.git" "${PREFIX}${r}"
	fi
done

